# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela/tela.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(371, 279)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(24, 87, 219, 141))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setSpacing(3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btn4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn4.setMaximumSize(QtCore.QSize(52, 32))
        self.btn4.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn4.setObjectName(_fromUtf8("btn4"))
        self.gridLayout_4.addWidget(self.btn4, 1, 0, 1, 1)
        self.btn5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn5.setMaximumSize(QtCore.QSize(52, 32))
        self.btn5.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn5.setObjectName(_fromUtf8("btn5"))
        self.gridLayout_4.addWidget(self.btn5, 1, 1, 1, 1)
        self.btn8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn8.setMaximumSize(QtCore.QSize(52, 32))
        self.btn8.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn8.setObjectName(_fromUtf8("btn8"))
        self.gridLayout_4.addWidget(self.btn8, 0, 1, 1, 1)
        self.btn3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn3.setMaximumSize(QtCore.QSize(52, 32))
        self.btn3.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn3.setObjectName(_fromUtf8("btn3"))
        self.gridLayout_4.addWidget(self.btn3, 2, 2, 1, 1)
        self.btn9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn9.setMaximumSize(QtCore.QSize(52, 32))
        self.btn9.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn9.setObjectName(_fromUtf8("btn9"))
        self.gridLayout_4.addWidget(self.btn9, 0, 2, 1, 1)
        self.btnDiv = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnDiv.setMaximumSize(QtCore.QSize(52, 32))
        self.btnDiv.setObjectName(_fromUtf8("btnDiv"))
        self.gridLayout_4.addWidget(self.btnDiv, 0, 3, 1, 1)
        self.btn7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn7.setMaximumSize(QtCore.QSize(52, 32))
        self.btn7.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn7.setObjectName(_fromUtf8("btn7"))
        self.gridLayout_4.addWidget(self.btn7, 0, 0, 1, 1)
        self.btn6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn6.setMaximumSize(QtCore.QSize(52, 32))
        self.btn6.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn6.setObjectName(_fromUtf8("btn6"))
        self.gridLayout_4.addWidget(self.btn6, 1, 2, 1, 1)
        self.btn1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn1.setMaximumSize(QtCore.QSize(52, 32))
        self.btn1.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn1.setObjectName(_fromUtf8("btn1"))
        self.gridLayout_4.addWidget(self.btn1, 2, 0, 1, 1)
        self.btn2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn2.setMaximumSize(QtCore.QSize(52, 32))
        self.btn2.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn2.setObjectName(_fromUtf8("btn2"))
        self.gridLayout_4.addWidget(self.btn2, 2, 1, 1, 1)
        self.btnSub = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnSub.setMaximumSize(QtCore.QSize(52, 32))
        self.btnSub.setObjectName(_fromUtf8("btnSub"))
        self.gridLayout_4.addWidget(self.btnSub, 2, 3, 1, 1)
        self.btnMult = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnMult.setMaximumSize(QtCore.QSize(52, 32))
        self.btnMult.setObjectName(_fromUtf8("btnMult"))
        self.gridLayout_4.addWidget(self.btnMult, 1, 3, 1, 1)
        self.btnSoma = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnSoma.setMaximumSize(QtCore.QSize(52, 32))
        self.btnSoma.setSizeIncrement(QtCore.QSize(32, 32))
        self.btnSoma.setObjectName(_fromUtf8("btnSoma"))
        self.gridLayout_4.addWidget(self.btnSoma, 3, 3, 1, 1)
        self.btnResto = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnResto.setMaximumSize(QtCore.QSize(52, 32))
        self.btnResto.setSizeIncrement(QtCore.QSize(32, 32))
        self.btnResto.setObjectName(_fromUtf8("btnResto"))
        self.gridLayout_4.addWidget(self.btnResto, 3, 2, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setMaximumSize(QtCore.QSize(52, 32))
        self.pushButton_19.setSizeIncrement(QtCore.QSize(32, 32))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_4.addWidget(self.pushButton_19, 3, 1, 1, 1)
        self.btn0 = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn0.setMaximumSize(QtCore.QSize(52, 32))
        self.btn0.setSizeIncrement(QtCore.QSize(32, 32))
        self.btn0.setObjectName(_fromUtf8("btn0"))
        self.gridLayout_4.addWidget(self.btn0, 3, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(24, 47, 331, 41))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.inputCalc = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.inputCalc.setObjectName(_fromUtf8("inputCalc"))
        self.verticalLayout_2.addWidget(self.inputCalc)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(245, 87, 111, 141))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setSpacing(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.undo = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.undo.setMaximumSize(QtCore.QSize(53, 32))
        self.undo.setObjectName(_fromUtf8("undo"))
        self.gridLayout_5.addWidget(self.undo, 0, 0, 1, 1)
        self.btnPaf = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnPaf.setMaximumSize(QtCore.QSize(53, 32))
        self.btnPaf.setObjectName(_fromUtf8("btnPaf"))
        self.gridLayout_5.addWidget(self.btnPaf, 1, 1, 1, 1)
        self.btnBck = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnBck.setMaximumSize(QtCore.QSize(53, 32))
        self.btnBck.setObjectName(_fromUtf8("btnBck"))
        self.gridLayout_5.addWidget(self.btnBck, 0, 1, 1, 1)
        self.btnPot = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnPot.setMaximumSize(QtCore.QSize(53, 32))
        self.btnPot.setObjectName(_fromUtf8("btnPot"))
        self.gridLayout_5.addWidget(self.btnPot, 2, 0, 1, 1)
        self.btnSqrt = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnSqrt.setMaximumSize(QtCore.QSize(53, 32))
        self.btnSqrt.setObjectName(_fromUtf8("btnSqrt"))
        self.gridLayout_5.addWidget(self.btnSqrt, 2, 1, 1, 1)
        self.btnPai = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnPai.setMaximumSize(QtCore.QSize(53, 33))
        self.btnPai.setObjectName(_fromUtf8("btnPai"))
        self.gridLayout_5.addWidget(self.btnPai, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnResult = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnResult.setObjectName(_fromUtf8("btnResult"))
        self.verticalLayout.addWidget(self.btnResult)
        self.gridLayout_5.addLayout(self.verticalLayout, 3, 0, 1, 2)
        self.resultText = QtGui.QLineEdit(self.centralwidget)
        self.resultText.setEnabled(False)
        self.resultText.setGeometry(QtCore.QRect(24, 20, 329, 25))
        self.resultText.setObjectName(_fromUtf8("resultText"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCalculadora = QtGui.QMenu(self.menubar)
        self.menuCalculadora.setObjectName(_fromUtf8("menuCalculadora"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionModo_Comum = QtGui.QAction(MainWindow)
        self.actionModo_Comum.setObjectName(_fromUtf8("actionModo_Comum"))
        self.actionModo_Avan_ado = QtGui.QAction(MainWindow)
        self.actionModo_Avan_ado.setObjectName(_fromUtf8("actionModo_Avan_ado"))
        self.menuCalculadora.addAction(self.actionModo_Comum)
        self.menuCalculadora.addAction(self.actionModo_Avan_ado)
        self.menubar.addAction(self.menuCalculadora.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn0, self.btn1)
        MainWindow.setTabOrder(self.btn1, self.btn2)
        MainWindow.setTabOrder(self.btn2, self.btn3)
        MainWindow.setTabOrder(self.btn3, self.btnSub)
        MainWindow.setTabOrder(self.btnSub, self.btn4)
        MainWindow.setTabOrder(self.btn4, self.btn5)
        MainWindow.setTabOrder(self.btn5, self.btn6)
        MainWindow.setTabOrder(self.btn6, self.btn7)
        MainWindow.setTabOrder(self.btn7, self.btn8)
        MainWindow.setTabOrder(self.btn8, self.btn9)
        MainWindow.setTabOrder(self.btn9, self.btnDiv)
        MainWindow.setTabOrder(self.btnDiv, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.btnResto)
        MainWindow.setTabOrder(self.btnResto, self.btnSoma)
        MainWindow.setTabOrder(self.btnSoma, self.btnPot)
        MainWindow.setTabOrder(self.btnPot, self.undo)
        MainWindow.setTabOrder(self.undo, self.btnBck)
        MainWindow.setTabOrder(self.btnBck, self.btnPaf)
        MainWindow.setTabOrder(self.btnPaf, self.btnPai)
        MainWindow.setTabOrder(self.btnPai, self.btnMult)
        MainWindow.setTabOrder(self.btnMult, self.btnSqrt)
        MainWindow.setTabOrder(self.btnSqrt, self.inputCalc)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btn4.setText(_translate("MainWindow", "4", None))
        self.btn5.setText(_translate("MainWindow", "5", None))
        self.btn8.setText(_translate("MainWindow", "8", None))
        self.btn3.setText(_translate("MainWindow", "3", None))
        self.btn9.setText(_translate("MainWindow", "9", None))
        self.btnDiv.setText(_translate("MainWindow", "/", None))
        self.btn7.setText(_translate("MainWindow", "7", None))
        self.btn6.setText(_translate("MainWindow", "6", None))
        self.btn1.setText(_translate("MainWindow", "1", None))
        self.btn2.setText(_translate("MainWindow", "2", None))
        self.btnSub.setText(_translate("MainWindow", "-", None))
        self.btnMult.setText(_translate("MainWindow", "*", None))
        self.btnSoma.setText(_translate("MainWindow", "+", None))
        self.btnResto.setText(_translate("MainWindow", "%", None))
        self.pushButton_19.setText(_translate("MainWindow", ",", None))
        self.btn0.setText(_translate("MainWindow", "0", None))
        self.undo.setText(_translate("MainWindow", "z", None))
        self.btnPaf.setText(_translate("MainWindow", ")", None))
        self.btnBck.setText(_translate("MainWindow", "<-", None))
        self.btnPot.setText(_translate("MainWindow", "x²", None))
        self.btnSqrt.setText(_translate("MainWindow", "sqrt", None))
        self.btnPai.setText(_translate("MainWindow", "(", None))
        self.btnResult.setText(_translate("MainWindow", "=", None))
        self.menuCalculadora.setTitle(_translate("MainWindow", "Calculadora", None))
        self.actionModo_Comum.setText(_translate("MainWindow", "Modo Comum", None))
        self.actionModo_Avan_ado.setText(_translate("MainWindow", "Modo Avançado", None))

